### ISSUE TITLE
app.blade.php absent

### ISSUE THREAD

**Issue by mohamedbelhassen** [ashraf777/Laravel-newsTicker#1]
Hello,

I tried to run  the project under Laravel 5.3.

the project fails due to an inclusion off absent template file: in the view (newsticker\index.blade.php), the template extends an absent template (@extends('app'))

how to solve this issue?

**Comment by ashraf777** [comment]
thnx for your response. 

You have to create your own (app.blade.php) view file.

**Comment by mohamedbelhassen** [comment]
could you share a sample one?
